name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Change to the shelfie directory
      - name: Change to shelfie directory
        run: cd shelfie

      # Install Flutter, configure web, and build web
      - name: Install Flutter and build web
        run: |
          sudo snap install flutter --classic
          flutter channel beta
          flutter config --enable-web
          flutter build web

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHELFIE_8BDC6 }}"
          channelId: live
          projectId: shelfie-8bdc6
